apiVersion: apps/v1
kind: Deployment
metadata:
  name: participant_a
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: participant_a
  template:
    metadata:
      labels:
        app: participant_a
    spec:
      containers:
        - name: participant_a
          image: amand1o/client-login:native # Replace with your actual client image
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          ports:
            - containerPort: 5000
        - name: measurer
          image: registry-git.lsd.ufcg.edu.br/amandio/iara:measurer
          args:
            [
              "app.py",
              "client",
              "$EXP_FINAL",
            ]
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_PTRACE
          stdin: true
          tty: true

---
apiVersion: v1
kind: Service
metadata:
  name: participant_a
  namespace: my-app
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000